/**
 * Build-time data preparation.
 *
 * The site's data lives in human-editable YAML/CSV under public/data/. None of
 * it changes at runtime, so we convert it to ready-to-use JSON here instead of
 * shipping YAML and CSV parsers to the browser and re-parsing on every page
 * load. A malformed edit now fails the build rather than the live site.
 */
import fs from 'node:fs';
import path from 'node:path';
import yaml from 'js-yaml';
import Papa from 'papaparse';

const DATA_DIR = 'public/data';

/** Files generated by this script; also listed in .gitignore. */
export const GENERATED = [
  'conferences.json',
  'csrankings.json',
  'core.json',
  'acceptance_rates.json',
];

/** Source files that should not be published to the deployed site. */
export const SOURCES = [
  'conferences.yaml',
  'csrankings_conferences.csv',
  'core_conferences.csv',
  'acceptance_rates.csv',
];

const read = (name) => fs.readFileSync(path.join(DATA_DIR, name), 'utf8');

const write = (name, value) =>
  fs.writeFileSync(path.join(DATA_DIR, name), JSON.stringify(value));

const parseCsv = (text) =>
  Papa.parse(text, { header: true, skipEmptyLines: true }).data;

/**
 * Groups a ranking CSV (CSRankings or CORE) into the shape the sidebar needs.
 */
function buildRanking(text) {
  const areasMap = {};
  const conferencesByArea = {};

  for (const row of parseCsv(text)) {
    const { AreaTitle: areaTitle, ParentArea: parentArea, ConferenceTitle: confName } = row;
    if (!areaTitle || !parentArea || !confName) continue;

    areasMap[parentArea] ??= [];
    const known = areasMap[parentArea].some(
      a => a.area_title === areaTitle && a.year === row.year && a.note === row.note
    );
    if (!known) {
      areasMap[parentArea].push({
        area: row.Area,
        area_title: areaTitle,
        year: row.year,
        note: row.note,
      });
    }

    conferencesByArea[areaTitle] ??= new Set();
    conferencesByArea[areaTitle].add(confName);
  }

  const byArea = Object.fromEntries(
    Object.entries(conferencesByArea).map(([area, names]) => [area, [...names]])
  );

  return {
    areasMap,
    conferencesByArea: byArea,
    allConferenceNames: Object.values(byArea).flat(),
  };
}

/**
 * Totals accepted/submitted per conference-year and derives the acceptance rate.
 */
function buildAcceptanceRates(text) {
  const stats = {};

  for (const row of parseCsv(text)) {
    if (!row.Conference || !row.Year) continue;
    const key = `${row.Conference}-${row.Year}`;
    stats[key] ??= { acceptance: 0, submission: 0 };
    stats[key].acceptance += Number(row.Accepted) || 0;
    stats[key].submission += Number(row.Submitted) || 0;
  }

  for (const entry of Object.values(stats)) {
    entry.acceptanceRate = entry.submission ? entry.acceptance / entry.submission : 0;
  }

  return stats;
}

/** Regenerates every JSON artifact. Throws if a source file is malformed. */
export function buildData() {
  const conferences = yaml.load(read('conferences.yaml'));
  if (!Array.isArray(conferences)) {
    throw new Error('conferences.yaml must parse to a list of conference entries');
  }

  write('conferences.json', conferences);
  write('csrankings.json', buildRanking(read('csrankings_conferences.csv')));
  write('core.json', buildRanking(read('core_conferences.csv')));
  write('acceptance_rates.json', buildAcceptanceRates(read('acceptance_rates.csv')));

  return conferences.length;
}

/**
 * Vite plugin: regenerate before dev/build, keep JSON fresh while editing, and
 * strip the YAML/CSV sources out of the published bundle.
 */
export default function dataPlugin() {
  let outDir = 'dist';

  return {
    name: 'csconfs-data',

    configResolved(config) {
      outDir = config.build.outDir;
    },

    buildStart() {
      const count = buildData();
      this.info?.(`prepared ${count} conference entries`);
    },

    configureServer(server) {
      // Serve the generated JSON explicitly. Vite snapshots publicDir when the
      // server starts, so files this plugin writes during buildStart are not
      // picked up on a first run in a fresh clone.
      const prefix = `${server.config.base}data/`;
      server.middlewares.use((req, res, next) => {
        const url = (req.url || '').split('?')[0];
        if (!url.startsWith(prefix)) return next();

        const name = url.slice(prefix.length);
        if (!GENERATED.includes(name)) return next();

        const file = path.join(DATA_DIR, name);
        if (!fs.existsSync(file)) return next();

        res.setHeader('Content-Type', 'application/json');
        res.setHeader('Cache-Control', 'no-store');
        res.end(fs.readFileSync(file));
      });

      const watched = SOURCES.map(f => path.resolve(DATA_DIR, f));
      server.watcher.add(watched);
      server.watcher.on('change', (file) => {
        if (!watched.includes(path.resolve(file))) return;
        try {
          buildData();
          server.config.logger.info(`[csconfs-data] regenerated from ${path.basename(file)}`);
          server.ws.send({ type: 'full-reload' });
        } catch (err) {
          server.config.logger.error(`[csconfs-data] ${err.message}`);
        }
      });
    },

    closeBundle() {
      // The browser only ever reads the generated JSON; don't publish the sources.
      for (const name of SOURCES) {
        fs.rmSync(path.join(outDir, 'data', name), { force: true });
      }
    },
  };
}
